#+Title: Run Virtual Labs on Virtual Box
#+Date: 24-10-2017
#+Author: VLEAD 

* Overview and Motivation
  Virtual Labs Team is providing a new approach to use/run Virtual
  Labs on any machine using *VirtualBox*.

  Visit [[https://www.virtualbox.org/wiki][VirtualBox]] for more details

  With this approach we can eliminate following things
  - Installing lab dependencies such adobe flash player on host
    machine
  - Browser types and versions


  Our main idea is to provide VirtualBox to lab users. The VirtualBox
  that we provide is, can be used for both Online and offline ( College
  Cloud)

  - Online Labs ::  Online labs are the labs that are running on the
                    AWS cloud. In order to use labs on your computer,
                    Internet connection is needed.

  - Offline Labs :: Offline labs are the labs that are running on the
                    College Cloud server. The College Cloud server is
                    a server that runs Virtual Labs on Campus/College
                    Local LAN. So that, Internet is not required to
                    run/use Virtual Labs.
		    
		    For more details about College Cloud, please visit
                    [[http://community.vlabs.ac.in/docs/user-manuals/college-cloud/][this link]]
* Audience
  Any Virtual Labs user 
* Systems Requirements for Running VirtualBox on your machine
  Minimum systems requirements
  1. At least 4GB RAM
  2. Dual Core processor

* Steps to use VirtualBox to run/use  Virtual Labs
** Install Virtual Box
   1. Visit the [[https://www.virtualbox.org/wiki/Downloads][VirtualBox provider]] link,
   2. Choose the appropriate VirtualBox version for your machine.

      It would be different from OS to OS. Like Linux machine may have
      different VirtualBox and Windows may have different VirtualBox,
      etc.
   3. Download appropriate VirtualBox
   4. Install VirtualBox On Windows
      1. Double click on *.exe* file
      2. Later, it would be asking for various options, provide the
         options and install it.
      3. After installation, you will be having virtuabox icon on your
         desktop
   5. Install VirtualBox on CentOS
      1. Download RPM package
	 #+BEGIN_EXAMPLE
	 wget http://download.virtualbox.org/virtualbox/5.1.6/VirtualBox-5.1-5.1.6_110634_el6-1.x86_64.rpm
	 #+END_EXAMPLE
      2. Install VirtualBox
	 #+BEGIN_EXAMPLE
	 sudo rpm -i VirtualBox-5.1-5.1.6_110634_el6-1.x86_64.rpm
	 #+END_EXAMPLE
** Import Virtual-Labs Virtual Box
   1. Download the *ubuntu-14.04-college-cloud.ova* from [[http://files.virtual-labs.ac.in/downloads/virtual-boxes/][here]] and save
      the file
   2. Double click on *ubuntu-14.04-college-cloud.ova* file.
   3. A window to import will be appeared.
   4. Import the file *ubuntu-14.04-college-cloud.ova* and follow the
      steps to install it. It may take a few minutes ( 5 to 10
      minutes)
   5. Once the importing is done, Select the
      *ubuntu-14.04-college-cloud* from the VirtualBox window. Please
      allocate the =Processor= and =Memory/RAM= size from the Settings
      menu appropriately.
   6. Start the box
   7. Credentials to login to *ubuntu-14.04-college-cloud*
      UserName : College Cloud
      Password : cc
   5. Open firefox, type [[http://vlabs.ac.in/][vlabs.ac.in]] 
   6. Then Start using the Virtual Labs

* Important note
  - Please do not upgrade Firefox version
  - Java dependent Labs would not be running on other browsers such as
    Google Chrome, Chromium, etc.
