#+Title: Run Virtual Labs on Virtual Box
#+Date: 24-10-2017
#+Author: VLEAD 

* Overview and Motivation
  Virtual Labs is providing a new approach to use/run Virtual
  Labs on any machine using [[https://www.virtualbox.org/wiki][VirtualBox]].

  This approach ensures the following:
  - Eliminates installation of dependencies such as Adobe Flash Player
    on user machine.
  - Eliminates dependency on browser types and versions.

   The VirtualBox that is provided by Virtual Labs can be used for
    both Online and Offline( College Cloud) versions of Virtual Labs.

   *Ofline version* ::

    [[https://info.vlabs.ac.in/college-cloud-edition/][Virtual Labs College Cloud Edition]] is the Offline and Portable
    Edition for Virtual Labs. It offers the offline version of Virtual
    labs, experiments and theoretical content. This edition addresses
    the lack of internet access or poor internet connectivity across
    different institutes/colleges.

   *Online version* ::

    [[https://info.vlabs.ac.in/workshops/][Virtual Labs online version]] can be accessed at all times from
    http://vlabs.ac.in.  It is dependent on a good Internet link.

* Audience
  Virtual Lab users.

* Systems Requirements
  Minimum systems requirements.
  1. 4GB RAM.
  2. Dual Core processor.

* VirtualBox installation steps
  1. Visit the [[https://www.virtualbox.org/wiki/Downloads][VirtualBox]] provider link. Please note that installation
     needs to be done only once.
  2. Choose the appropriate VirtualBox version based on the Operating
     System ( OS ) installed on the machine.
  3. Download the selected VirtualBox.
  4. VirtualBox installation steps on Windows OS
     1. Double click on *.exe* file.
     2. Follow the instructions appearing on installation wizard
     3. After installation, ensure that a VirtualBox icon is created
        on the desktop.
  5. VirtualBox installation steps on CentOS OS
     1. Download RPM package.
	#+BEGIN_EXAMPLE
	wget http://download.virtualbox.org/virtualbox/5.1.6/VirtualBox-5.1-5.1.6_110634_el6-1.x86_64.rpm
	#+END_EXAMPLE
	
     2. Install VirtualBox.
	#+BEGIN_EXAMPLE
	sudo rpm -i VirtualBox-5.1-5.1.6_110634_el6-1.x86_64.rpm
	#+END_EXAMPLE

  6. Ubuntu 14.04.
     1) Download VirtualBox.
	#+BEGIN_EXAMPLE
	wget http://download.virtualbox.org/virtualbox/5.2.0/virtualbox-5.2_5.2.0-118431~Ubuntu~trusty_amd64.deb
	#+END_EXAMPLE

     2) Install VirtualBox.
	#+BEGIN_EXAMPLE
	sudo dpkg -i virtualbox-5.2_5.2.0-118431~Ubuntu~trusty_amd64.deb
	#+END_EXAMPLE
  7. Steps 5 and 6 are installation step examples for CentOS-6.x and
     Ubuntu 14.04. These installation steps will vary based on the
     version of the OS installed on the user machine.  Please follow
     the [[https://www.virtualbox.org/wiki/Linux_Downloads][link]] for appropriate steps.

* Virtual-Labs VirtualBox import steps  
  1. Follow the [[http://files.virtual-labs.ac.in/downloads/virtual-boxes/][link]] to download and save the
     *ubuntu-14.04-college-cloud.ova*. Please note that import steps
     need to be done only once.
  2. Double click on the *ubuntu-14.04-college-cloud.ova* file.
  3. A import window will appear.
  4. Import the file *ubuntu-14.04-college-cloud.ova* and follow the
     steps to install it. This may take 5 to 10  minutes.
  5. On completion of step 4, select the *ubuntu-14.04-college-cloud*
     from the VirtualBox window. Please allocate the =Processor= and
     =Memory/RAM= size from the Settings menu appropriately based on
     the system configuration of the user machine.
     
     Recommended Settings for the imported box
     #+BEGIN_EXAMPLE
     Processor --> 1
     Memory/RAM size --> 1GB
     #+END_EXAMPLE

* Using VirtualBox to run Virtual Labs
  1. Windows Users: Double click the VirtualBox icon on the desktop to
     start the VirtualBox.
  2. Linux Users (CentOS, Debian, Ubuntu, etc): Search for VirtualBox
     on user machine. 
  3. Select and Start *ubuntu-14.04-college-cloud* box.
  4. Login to *ubuntu-14.04-college-cloud* using the following
     credentials:
     UserName : College Cloud
     Password : cc
  5. Open Firefox and type [[http://vlabs.ac.in/][vlabs.ac.in]] to use Virtual Labs.
  6. These steps need to be followed every time for accessing Virtual
     Labs using VirtualBox.

* NOTE
  - Please use only Firefox ( provided in the VirtualBox ) to use
    Virtual Labs.
  - Please do not upgrade Firefox version in the VirtualBox.

